
package cricknewsofficial;

/**
 *
 * @author Mihindu Ranasinghe
 */
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.*;


public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LabelEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        LabelPass = new javax.swing.JLabel();
        LabelConfirmpass = new javax.swing.JLabel();
        txtConfirmPass = new javax.swing.JPasswordField();
        btnSignup = new javax.swing.JButton();
        LabelCountry = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtCountry = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelEmail.setBackground(new java.awt.Color(204, 204, 204));
        LabelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelEmail.setForeground(new java.awt.Color(204, 204, 204));
        LabelEmail.setText("Email");
        LabelEmail.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(LabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 84, 22));

        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 204, 204)));
        txtEmail.setOpaque(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 320, 30));

        LabelPass.setBackground(new java.awt.Color(204, 204, 204));
        LabelPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelPass.setForeground(new java.awt.Color(204, 204, 204));
        LabelPass.setText("Password");
        jPanel2.add(LabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 84, 23));

        LabelConfirmpass.setBackground(new java.awt.Color(204, 204, 204));
        LabelConfirmpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelConfirmpass.setForeground(new java.awt.Color(204, 204, 204));
        LabelConfirmpass.setText("confirm Password");
        jPanel2.add(LabelConfirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, 23));

        txtConfirmPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 204, 204)));
        txtConfirmPass.setOpaque(false);
        txtConfirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPassActionPerformed(evt);
            }
        });
        jPanel2.add(txtConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 320, 30));

        btnSignup.setText("Submit");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        jPanel2.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, -1));

        LabelCountry.setBackground(new java.awt.Color(204, 204, 204));
        LabelCountry.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCountry.setForeground(new java.awt.Color(204, 204, 204));
        LabelCountry.setText("Your Country");
        jPanel2.add(LabelCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, 23));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mihindu Ranasinghe\\Desktop\\user3.png")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 130, 120));

        txtPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 204, 204)));
        txtPass.setOpaque(false);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        jPanel2.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 320, 30));

        txtCountry.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 204, 204)));
        txtCountry.setOpaque(false);
        txtCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryActionPerformed(evt);
            }
        });
        jPanel2.add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 397, 320, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mihindu Ranasinghe\\Desktop\\stick-cricket-icon.png")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 179, -1));

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Welcome to CrickNEWS Official ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 710, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConfirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPassActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
        DbConnection db=new DbConnection();
        Connection cn=db.createScreen();

        String email,pw,cpw,country;
        email=txtEmail.getText();
        pw=String.valueOf(txtPass.getPassword());
        cpw=String.valueOf(txtConfirmPass.getPassword());
        country=txtCountry.getText();

        try{
            Statement st=cn.createStatement();
            if(pw.equals(cpw)){
                st.executeUpdate("insert into users(email,password,country) values('"+email+"','"+pw+"','"+country+"')");
                JOptionPane.showConfirmDialog(null,"User added to the system");
                login logn=new login();
                logn.setVisible(true);
                dispose();
                
                
                

            }
            else{
                JOptionPane.showConfirmDialog(null, "Password Missmatch. Please enter the same password for both fieds");
            }

        }
        catch(SQLException e1){
            System.out.println(e1.getMessage());
        }

    }//GEN-LAST:event_btnSignupActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryActionPerformed

    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelConfirmpass;
    private javax.swing.JLabel LabelCountry;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelPass;
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
